server:
  port: 6063
  servlet:
    context-path: /ecommerce

spring:
  application:
    name: authentication-svc
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
app:
  api-key: ecommerce-app-api-key-1234  # app-level key

jwt:
  secret: 3mR6VwzJ2sP4eYh7M9tZ1bKx0uQ5rNnCkL8vF2pH1tY=  # secure random secret, 32+ bytes
  access-expiration: 1800             # in seconds (30 min)
  refresh-expiration: 604800          # in seconds (7 days)

logging:
  level:
    org.springframework.security: DEBUG
